-- ================================================================
-- TABLE 1: cost_type
-- ================================================================
CREATE TABLE cost_type
(
    cost_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name    VARCHAR(100) NOT NULL UNIQUE,
    description  VARCHAR(255)
);

-- ================================================================
-- TABLE 2: shipment
-- ================================================================
CREATE TABLE shipment
(
    shipment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_ref  VARCHAR(100) NOT NULL UNIQUE,
    description   VARCHAR(255),
    shipment_date DATE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profitloss    DECIMAL(18, 2)
);

-- ================================================================
-- TABLE 3: income
-- ================================================================
CREATE TABLE income
(
    income_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT         NOT NULL,
    amount      DECIMAL(18, 2) NOT NULL CHECK (amount > 0),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_income_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipment (shipment_id)
            ON DELETE CASCADE
);

-- ================================================================
-- TABLE 4: cost
-- ================================================================
CREATE TABLE cost
(
    cost_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id     BIGINT         NOT NULL,
    cost_type_id    BIGINT         NOT NULL,
    amount          DECIMAL(18, 2) NOT NULL CHECK (amount >= 0),
    additional_cost DECIMAL(18, 2) NOT NULL DEFAULT 0 CHECK (additional_cost >= 0),
    created_at      TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cost_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipment (shipment_id)
            ON DELETE CASCADE,
    CONSTRAINT fk_cost_type
        FOREIGN KEY (cost_type_id) REFERENCES cost_type (cost_type_id)
);

-- ================================================================
-- INDEXES
-- ================================================================
CREATE INDEX idx_income_shipment_id ON income (shipment_id);
CREATE INDEX idx_cost_shipment_id ON cost (shipment_id);
CREATE INDEX idx_cost_type_id ON cost (cost_type_id);

